# Generated by Django 5.1.1 on 2024-12-02 21:32

import app_gestao_financeira.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=50, verbose_name='Tipo de Relatório')),
                ('data', models.DateField(verbose_name='Data')),
                ('conteudo', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_liquido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Patrimônio Líquido')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('dividas', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dívidas')),
                ('metas', models.TextField(blank=True, null=True, verbose_name='Metas')),
                ('perfil', models.CharField(choices=[('Conservador', 'Conservador'), ('Moderado', 'Moderado'), ('Arrojado', 'Arrojado'), ('Agressivo', 'Agressivo'), ('Balanceado', 'Balanceado')], max_length=50, verbose_name='Perfil')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=app_gestao_financeira.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Investimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Fundos', 'Fundos'), ('Ações', 'Ações'), ('Tesouro', 'Tesouro'), ('CDB', 'CDB'), ('Imóveis', 'Imóveis'), ('Criptomoedas', 'Criptomoedas'), ('Previdência Privada', 'Previdência Privada'), ('Outros', 'Outros')], default='Outros', max_length=50, verbose_name='Tipo de Investimento')),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Investido')),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rentabilidade')),
                ('investimentos_fisicos', models.TextField(blank=True, null=True, verbose_name='Investimentos Físicos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='DespesasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Comida', 'Comida'), ('Festas', 'Festas'), ('Passeios', 'Passeios'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Outros', 'Outros')], default='Outros', max_length=50, verbose_name='Tipo de Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Despesa Extra',
                'verbose_name_plural': 'Despesas Extras',
            },
        ),
        migrations.CreateModel(
            name='CustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Custo Fixo',
                'verbose_name_plural': 'Custos Fixos',
            },
        ),
    ]
