# Generated by Django 5.1.1 on 2024-10-10 16:26

import app_gestao_financeira.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesa',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Relatório')),
                ('data', models.DateField(verbose_name='Data')),
                ('conteudo', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Patrimônio Líquido')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('dividas', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Dívidas')),
                ('metas', models.TextField(blank=True, null=True, verbose_name='Metas')),
                ('perfil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Perfil')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=app_gestao_financeira.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Investimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Investimento')),
                ('valor_investido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Investido')),
                ('rentabilidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rentabilidade')),
                ('investimentos_fisicos', models.TextField(blank=True, null=True, verbose_name='Investimentos Físicos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='DespesasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.tipodespesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Despesa Extra',
                'verbose_name_plural': 'Despesas Extras',
            },
        ),
        migrations.CreateModel(
            name='CustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_financeira.usuario')),
            ],
            options={
                'verbose_name': 'Custo Fixo',
                'verbose_name_plural': 'Custos Fixos',
            },
        ),
    ]
