# Generated by Django 5.1.1 on 2024-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_financeira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesasextras',
            name='tipo',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Festas', 'Festas'), ('Passeios', 'Passeios'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Outros', 'Outros')], default='Outros', max_length=50, verbose_name='Tipo de Despesa'),
        ),
        migrations.DeleteModel(
            name='TipoDespesa',
        ),
    ]
