# Generated by Django 5.1.1 on 2024-10-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_financeira', '0002_alter_despesasextras_tipo_delete_tipodespesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimentos',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fundos', 'Fundos'), ('Ações', 'Ações'), ('Tesouro', 'Tesouro'), ('CDB', 'CDB'), ('Imóveis', 'Imóveis'), ('Criptomoedas', 'Criptomoedas'), ('Previdência Privada', 'Previdência Privada'), ('Outros', 'Outros')], default='Outros', max_length=50, null=True, verbose_name='Tipo de Investimento'),
        ),
    ]
