# Generated by Django 5.1.1 on 2024-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_financeira', '0003_alter_investimentos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=50, verbose_name='Tipo de Relatório'),
        ),
    ]
